#!/usr/bin/env bash
#  uses ssh to connect to your server using 
#the private key ~/.ssh/school with the user ubuntu
ssh -i ~/.ssh/school ubuntu@35.153.93.12
ssh -i ~/.ssh/school ubuntu@54.237.19.219
